Add password check

diff --git a/homemgr b/homemgr
--- a/homemgr
+++ b/homemgr
@@ -146,7 +146,6 @@ if [ "$(getent passwd $3)" ]; then
 	echo "User with UID $3 already exists"
 	exit 4
 fi
-	if [ "$5" ]; then U_PASSWORD="--password $5"; else U_PASSWORD=; fi
 	if [ "$4" ]; then
 		if [ ! -f $4 ]; then
 			echo "shell $4 not exists"
@@ -160,7 +159,7 @@ fi
 	if [ -d /etc/skel ]; then
 	SKEL_SETUP="--skel /etc/skel"
 	else SKEL_SETUP=; fi
-	useradd $GID_SETUP --uid $3 $SKEL_SETUP $U_SHELL $U_PASSWORD --create-home $2
+	useradd $GID_SETUP --uid $3 $SKEL_SETUP $U_SHELL --create-home $2
 	temp_UID="$3"
 	temp_GID="$(getent passwd $2 | cut -d":" -f4)"
 	temp_GID_W="$2"
@@ -174,7 +173,8 @@ H_GID_W=$temp_GID_W
 H_SHELL=$temp_SHL
 H_GROUPS="$temp_GRS"
 EOF
-	if [ "$5" ]; then echo "H_PASSWORD=\"$5\"" >>/home/$2/.homedata; fi
+	if [ "$5" ]; then echo "H_PASSWORD=\"$5\"" >>/home/$2/.homedata
+	echo "$2:$5" | chpasswd -c SHA512; fi
 	chmod 000 /home/$2/.homedata
 	chattr +i /home/$2/.homedata
 	echo "Done."
@@ -341,11 +341,12 @@ if [[ "$3" == "-n" || "$3" == "--no-useradd" ]]; then
 			else
 				U_SHELL="--shell $H_SHELL"
 			fi
-			useradd $GID_SETUP $UID_SETUP $U_SHELL $U_PASSWORD --home-dir /home/$_USERNAME $_USERNAME
+			useradd $GID_SETUP $UID_SETUP $U_SHELL --home-dir /home/$_USERNAME $_USERNAME
 			tar --verbose --extract --same-owner --same-permissions --group="$H_GID_W" --file $2 --directory=/home || {
 				echo "Error occured"
 				exit 6
 			}
+			if [ -n "$H_PASSWORD" ]; then echo "$_USERNAME:$H_PASSWORD" | chpasswd -c SHA512 || echo "Error occured while changing password"; fi
 			import_groups
 			echo "Done."
 			exit 0
@@ -366,6 +367,7 @@ if [[ "$3" == "-n" || "$3" == "--no-useradd" ]]; then
 				echo "Error occured"
 				exit 6
 			}
+			if [ -n "$H_PASSWORD" ]; then echo "$_USERNAME:$H_PASSWORD" | chpasswd -c SHA512 || echo "Error occured while changing password"; fi
 			import_groups
 			echo "Done."
 			exit 0
